# Generated by Django 5.1.6 on 2025-02-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
    ]
