# Generated by Django 5.1.6 on 2025-03-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250226_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('trendID', models.AutoField(primary_key=True, serialize=False)),
                ('indexName', models.CharField(max_length=255)),
                ('trendData', models.JSONField()),
                ('marketVolatility', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockID', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('companyName', models.CharField(max_length=255)),
                ('currentPrice', models.FloatField()),
                ('peRatio', models.FloatField()),
                ('pbRatio', models.FloatField()),
                ('dividendYield', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='accountBalance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privileges', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeginnerInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experienceLevel', models.CharField(max_length=50)),
                ('preferredInvestmentType', models.CharField(max_length=100)),
                ('riskTolerance', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=255)),
                ('yearsOfExperience', models.IntegerField()),
                ('clientList', models.ManyToManyField(blank=True, related_name='advisor_clients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experienceLevel', models.CharField(max_length=50)),
                ('portfolioSize', models.FloatField()),
                ('tradingStrategy', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationEngine',
            fields=[
                ('recommendationID', models.AutoField(primary_key=True, serialize=False)),
                ('recommendationCriteria', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommendedStocks', models.ManyToManyField(blank=True, to='myapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolioID', models.AutoField(primary_key=True, serialize=False)),
                ('riskLevel', models.CharField(max_length=50)),
                ('totalInvestment', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stocks', models.ManyToManyField(blank=True, to='myapp.stock')),
            ],
        ),
    ]
