# Generated by Django 5.1.6 on 2025-03-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_stock_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividendYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pbRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='peRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='company',
        ),
    ]
