# Generated by Django 5.1.6 on 2025-03-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_watchlist_unique_together_watchlist_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.stock'),
        ),
    ]
