# Generated by Django 5.1.6 on 2025-03-22 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_watchlist_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stock'),
        ),
    ]
